apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
      - name: nodejs-app
        image: us-central1-docker.pkg.dev/your-gcp-project-id/nodejs-mongodb-repo/nodejs-app:latest
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_URI
          value: "mongodb://mongo:27017/mydb"
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-app-service
  namespace: default
spec:
  selector:
    app: nodejs-app
  ports:
  - port: 3000
    targetPort: 3000
  type: LoadBalancer
