apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nodejs-app-monitor
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: nodejs-app
  endpoints:
  - port: web
    path: /metrics
    interval: 15s
  namespaceSelector:
    matchNames:
    - default
